Repository gememma/wirebrush, pull requests merged in 2023-10, with the labels that each got.

#60 Hotfix: convert markdown links to HTML links
  content/projects.md
Labels: T-bug

#65 Use updated CV version with degree classification
  static/cv.pdf
Labels: T-chore

#63 Convert all files to LF line endings instead of CRLF
  LICENSE-APACHE
  LICENSE-MIT
  build.rs
  content/home.md
  content/projects.md
  rust-toolchain.toml
  scss/style.scss
  src/handler.rs
Labels: T-chore, D-easy
