Repository gememma/wirebrush, pull requests merged in 2023-08, with the labels that each got.

#42 Read in posts from the content directory
  Cargo.lock
  content/about.md
  src/main.rs
Labels: T-feature, D-medium, I-core, A-rust

#44 Add favicon files and serve favicons at /static/[file].png
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/templates.rs
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
Labels: I-nice-to-have, A-rust

#43 Add pulldown-cmark to parse markdown in content files
  Cargo.lock
  Cargo.toml
  content/about.md
  src/main.rs
Labels: T-feature, D-hard, I-nice-to-have, A-rust

#48 Move handler functions to handler module
  src/handler.rs
  src/main.rs
Labels: T-feature, D-easy, A-rust

#51 Add navbar
  scss/style.scss
  src/templates.rs
Labels: T-feature

#52 Add a Nix flake, including a Nix package, for wirebrush
  .envrc
  .gitignore
  Cargo.nix
  flake.lock
  flake.nix
Labels: T-chore

#58 Alter wording on projects page
  content/projects.md
Labels: T-improvement, D-easy
